
# image 문을 사용해 이미지를 정의합니다.
# image eileen happy = "eileen_happy.png"

image SH Si = "서광호 정장.png"
image SH Si2 = "서광호 정장 한숨.png"
image SH Si3 = "서광호 정장 놀람.png"
image SH Si4 = "서광호 정장 억지웃음.png"
image SH Si5 = "서광호 정장 화남.png"
image SH Si6 = "서광호 정장 눈물.png"
image SH Si7 = "서광호 정장 살짝 웃는.png"
image SH Si8 = "서광호 정장 머쓱한.png"

image SH Pa = "서광호 잠옷.png"
image SH Pa2 = "서광호 잠옷 한숨.png"
image SH Pa3 = "서광호 잠옷 놀람.png"
image SH Pa5 = "서광호 잠옷 화남.png"
image SH Pa6 = "서광호 잠옷 눈물.png"

image SH Gn = "서광호 가운.png"
image SH Gn2 = "서광호 가운 한숨.png"
image SH Gn3 = "서광호 가운 놀람.png"
image SH Gn5 = "서광호 가운 화남.png"
image SH Gn6 = "서광호 가운 눈물.png"

image IZ Ii = "이연조 정장.png"
image IZ Ii2 = "이연조 정장 곤란.png"
image IZ Ii3 = "이연조 정장 눈치.png"
image IZ Ii4 = "이연조 정장 놀람.png"
image IZ Ii5 = "이연조 정장 신난.png"
image IZ Ii6 = "이연조 정장 화난.png"
image IZ Ii7 = "이연조 정장 지각.png"
image IZ Ii8 = "이연조 정장 반짝이는.png"
image IZ Ii9 = "이연조 정장 부끄러운.png"
image IZ Ii10 = "이연조 정장 신기한.png"
image IZ Ii11 = "이연조 정장 싸늘한.png"
image IZ Ii12 = "이연조 정장 아쉬운.png"
image IZ Ii13 = "이연조 정장 자는.png"
image IZ Ii14 = "이연조 정장 조금 놀란.png"
image IZ Ii15 = "이연조 정장 조금 신난.png"
image IZ Ii16 = "이연조 정장 허둥지둥.png"

image IZ In = "이연조 파티.png"
image IZ In2 = "이연조 파티 곤란.png"
image IZ In3 = "이연조 파티 눈치.png"
image IZ In4 = "이연조 파티 놀람.png"
image IZ In5 = "이연조 파티 신난.png"
image IZ In6 = "이연조 파티 화난.png"
image IZ In7 = "이연조 파티 지각.png"
image IZ In8 = "이연조 파티 반짝이는.png"
image IZ In9 = "이연조 파티 부끄러운.png"
image IZ In10 = "이연조 파티 신기한.png"
image IZ In11 = "이연조 파티 싸늘한.png"
image IZ In12 = "이연조 파티 아쉬운.png"
image IZ In13 = "이연조 파티 자는.png"
image IZ In14 = "이연조 파티 조금 놀란.png"
image IZ In15 = "이연조 파티 조금 신난.png"

image bgS SKL = "서광호 주방&거실.png"
image bgS SB1 = "서광호 침실.png"
image bgS SB2 = "서광호 욕실.png"
image bgS SC = "서광호 차.png"
image bgS OE = "회사.png"
image bgS PT = "주차장.png"
image bgS RD = "도로.png"
image bgS HY = "세미나 호텔복도.png"
image bgS HM = "세미나실.png"
image bgS MT = "시장.png"
image bgS AE = "비행기 내부.png"
image bgS HR = "호텔방.png"
image bgS OY = "전망대.png"
image bgS HP = "호텔 옥상.png"
image bgS HY2 = "파티 호텔 복도.png"
image bgS DP = "양복점.png"
image bgS HB = "호텔 바.png"
image bgS HH = "파티장.png"

image black = "검정.jpg"

image loveEnding = "연애.png"
image GGEnding = "광공.png"

image nightView = "야경.png"
